# Generated by Django 2.2.3 on 2019-07-31 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnnotatingXmlContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_symbol', models.CharField(max_length=255)),
                ('xml_content', models.TextField()),
            ],
        ),
    ]
