version: '3'

services:
  postgres:
    build:
      ./postgres/
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: "collaborative_platform"
      POSTGRES_PASSWORD: "collapass"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    stdin_open: true

  elasticsearch:
    image: elasticsearch:7.3.2
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      - discovery.type=single-node
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - elasticsearch_data_vol:/usr/share/elasticsearch/data
    stdin_open: true

  redis:
    image: redis

  celery:
    build:
      context: "."
    working_dir: /code/src/collaborative_platform
    command: celery -A collaborative_platform worker -B -l DEBUG -E
    volumes:
      - .:/code
    depends_on:
      - "redis"
    restart: "${DOCKER_RESTART_POLICY:-unless-stopped}"
    stop_grace_period: "${DOCKER_STOP_GRACE_PERIOD:-3s}"

  web:
    build: .
    command: python src/collaborative_platform/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - 8000:8000
    depends_on:
      - postgres
      - elasticsearch
      - redis
      - celery
    stdin_open: true

volumes:
  db-data:
    external: false
    driver: local
  elasticsearch_data_vol:
    external: false
    driver: local
