#!/bin/bash
cd /home/ubuntu/collaborative-platform
pkill screen
git pull --rebase
cd src/collaborative_platform/
cp collaborative_platform/settings.py_template collaborative_platform/settings.py
cat /home/ubuntu/secrets >> collaborative_platform/settings.py
python3 manage.py makemigrations
python3 manage.py migrate
rm -r ~/collaborative-platform/static/*
python3 manage.py collectstatic
screen -d -m uwsgi --socket /home/ubuntu/collaborative-platform/src/collaborative_platform/collaborative_platform.sock --chmod-socket=666 --module collaborative_platform.wsgi
screen -d -m daphne -u collaborative_platform_websockets.sock collaborative_platform.asgi:application
screen -d -m celery -A collaborative_platform worker -B -l DEBUG -E