#!/bin/bash
docker-compose stop web elasticsearch redis postgres celery
docker system prune --volumes -f
rm -f src/collaborative_platform/apps/*/migrations/0*.py
rm -f media/uploaded_files/*
rm -f media/NN_Models/*
docker-compose build
docker-compose up -d elasticsearch postgres
sleep 5
docker-compose run web python src/collaborative_platform/manage.py makemigrations
docker-compose run web python src/collaborative_platform/manage.py migrate
docker-compose run web python src/collaborative_platform/manage.py shell -c "from apps.index_and_search.initialize import initialize; initialize()"
docker-compose run web python src/collaborative_platform/manage.py loaddata core_initial.json
