# Generated by Django 2.2.3 on 2019-07-25 13:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('agree_to_terms', models.BooleanField(default=True)),
                ('is_scientist', models.BooleanField(default=False)),
                ('orcid', models.CharField(blank=True, max_length=19, null=True)),
                ('twitter', models.CharField(blank=True, max_length=20, null=True)),
                ('github', models.CharField(blank=True, max_length=20, null=True)),
                ('scholar', models.CharField(blank=True, max_length=20, null=True)),
                ('researchgate', models.CharField(blank=True, max_length=20, null=True)),
                ('about', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
    ]
