# Generated by Django 2.2.3 on 2019-07-25 13:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Directory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('parent_dir', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='files_management.Directory')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.Project')),
            ],
            options={
                'unique_together': {('parent_dir', 'name')},
            },
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('version_number', models.PositiveIntegerField()),
                ('parent_dir', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='files_management.Directory')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.Project')),
            ],
            options={
                'unique_together': {('parent_dir', 'name')},
            },
        ),
        migrations.CreateModel(
            name='FileVersion',
            fields=[
                ('upload', models.FileField(upload_to='files/')),
                ('hash', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('number', models.PositiveIntegerField()),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='files_management.File')),
            ],
            options={
                'unique_together': {('file', 'number')},
            },
        ),
    ]
