apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: celery
spec:
  output:
    to:
      kind: ImageStreamTag
      name: 'celery:latest'
  postCommit: {}
  resources:
    limits:
      cpu: '4'
      memory: 4Gi
    requests:
      cpu: '1'
      memory: 1Gi
  runPolicy: Serial
  source:
    git:
      ref: master
      uri: 'https://github.com/providedh/collaborative-platform'
    type: Git
  strategy:
    dockerStrategy:
      dockerfilePath: kubernetes/celery/Dockerfile
    type: Docker
