apiVersion: v1
kind: DeploymentConfig
metadata:
  labels:
    app: celery
    app.kubernetes.io/component: celery
    app.kubernetes.io/instance: celery
  name: celery
spec:
  replicas: 1
  selector:
    io.kompose.service: celery
    matchLabels:
      deployment: celery
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: Rolling
  template:
    metadata:
      labels:
        deployment: celery
    spec:
      containers:
        - args: ["cd /app/src/collaborative_platform && celery -A collaborative_platform worker -B -l DEBUG -E"]
          command: ["/bin/bash"]
          image: 'celery:latest'
          name: celery
          resources: {}
          stdin: true
          volumeMounts:
            - mountPath: /app
              name: app
      restartPolicy: Always
      volumes:
        - name: app
          persistentVolumeClaim:
            claimName: app
  test: false
  triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: true
        containerNames:
          - celery
        from:
          kind: ImageStreamTag
          name: celery:latest
      type: ImageChange

