apiVersion: v1
kind: Service
metadata:
  labels:
    app: celery
    app.kubernetes.io/component: celery
    app.kubernetes.io/instance: celery
  name: celery
spec:
  ports:
    - name: 8080-tcp
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    deployment: celery