apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.22.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: elasticsearch
  name: elasticsearch
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: elasticsearch
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.22.0 (HEAD)
      creationTimestamp: null
      labels:
        io.kompose.service: elasticsearch
    spec:
      containers:
        - env:
            - name: ES_JAVA_OPTS
              value: -Xmx1024m -Xms1024m
            - name: LimitMEMLOCK
              value: infinity
            - name: LimitNOFILE
              value: "65536"
            - name: TimeoutStopSec
              value: "0"
            - name: discovery.type
              value: single-node
          image: elasticsearch:7.3.2
          name: elasticsearch
          ports:
            - containerPort: 9200
            - containerPort: 9300
          resources: {}
          stdin: true
          volumeMounts:
            - mountPath: /usr/share/elasticsearch/data
              name: elasticsearch-data-vol
      restartPolicy: Always
      volumes:
        - name: elasticsearch-data-vol
          persistentVolumeClaim:
            claimName: elasticsearch-data-vol
status: {}
