apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: media
  name: media
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 30Gi
status: {}
