apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: nginx
spec:
  output:
    to:
      kind: ImageStreamTag
      name: 'nginx:latest'
  postCommit: {}
  resources:
    limits:
      cpu: 2
      memory: 4Gi
    requests:
      cpu: 1
      memory: 1Gi
  runPolicy: Serial
  source:
    git:
      ref: master
      uri: 'https://github.com/providedh/collaborative-platform'
    type: Git
  strategy:
    dockerStrategy:
      dockerfilePath: kubernetes/nginx/Dockerfile
    type: Docker
