apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.22.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: postgres
  name: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: postgres
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.22.0 (HEAD)
      creationTimestamp: null
      labels:
        io.kompose.service: postgres
    spec:
      containers:
        - env:
            - name: PGDATA
              value: /var/lib/postgresql/data/pgdata
            - name: PG_PASSWORD
              value: Pr0viD3Dh
            - name: PG_ROOT_PASSWORD
              value: Pr0viD3Dh
            - name: PG_USER
              value: collaborative_platform
            - name: PG_PRIMARY_USER
              value: collaborative_platform
            - name: PG_PRIMARY_PASSWORD
              value: Pr0viD3Dh
            - name: PG_PRIMARY_PORT
              value: "5432"
            - name: PG_DATABASE
              value: collaborative_platform
            - name: MODE
              value: postgres
            - name: PG_MODE
              value: primary
          image: crunchydata/crunchy-postgres-gis:centos8-13.2-3.0-4.6.1
          name: postgres
          ports:
            - containerPort: 5432
          resources: {}
          stdin: true
          volumeMounts:
            - mountPath: /pgdata
              name: db-data
      restartPolicy: Always
      volumes:
        - name: db-data
          persistentVolumeClaim:
            claimName: db-data
status: {}
