apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.22.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: postgres
  name: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: postgres
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.22.0 (HEAD)
      creationTimestamp: null
      labels:
        io.kompose.service: postgres
    spec:
      containers:
        - env:
            - name: PGDATA
              value: /var/lib/postgresql/data/pgdata
            - name: POSTGRES_USER
                valueFrom:
                  secretKeyRef:
                    key: database-user
                    name: postgres
            - name: POSTGRES_PASSWORD
                valueFrom:
                  secretKeyRef:
                    key: database-password
                    name: postgres
            - name: POSTGRES_DATABASE
                valueFrom:
                  secretKeyRef:
                    key: database-name
                    name: postgres
          image: postgres
          name: postgres
          ports:
            - containerPort: 5432
          resources: { }
          stdin: true
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: db-data
      restartPolicy: Always
      volumes:
        - name: db-data
          persistentVolumeClaim:
            claimName: db-data
status: { }
